/*Updating the SPORTS_TEAM with the teams coaches names*/
UPDATE SPORTS_TEAM
SET TEAMCOACH = 'DAVID WILLIAMS'
WHERE teamname = 'Penguins';

UPDATE SPORTS_TEAM
SET TEAMCOACH = 'JOHN SMITH'
WHERE teamname = 'Dolphins';

UPDATE SPORTS_TEAM
SET TEAMCOACH = 'SCOTT RUSSEL'
WHERE teamname = 'Sharks';


UPDATE PLAYER_DATA
SET TEAMCOACH = 'DAVID WILLIAMS'
WHERE TEAMID = 1;

UPDATE PLAYER_DATA
SET TEAMCOACH = 'JOHN SMITH'
WHERE TEAMID = 2;

UPDATE PLAYER_DATA
SET TEAMCOACH = 'SCOTT RUSSEL'
WHERE TEAMID = 3;