/* CREATING TABLE SPORTS_TEAM FOR THE LIST OF TEAMS AND USING DATATYPES AND DATASIZE FOR EACH ROWS AND COLUMNS INCLUDING CONSTRAINT THAT WILL USE THE PRIMARY KEY TEAMID*/
CREATE TABLE SPORTS_TEAM
(
  Teamid NUMBER(3,0), 
  City VARCHAR2(255 char),
  Teamname VARCHAR2(255 char),
 CONSTRAINT sports_team_id_pk PRIMARY KEY(TEAMID));
 
/* CREATING PLAYER_DATA TABLE USING THE CREATE TABLE COMMAND AND INSERTING DATATYPES AND DATASIZE TO EACH ROWS AND COLUMNS USING THE FOREIGN KEY FOR THE TEAMID*/

CREATE TABLE PLAYER_DATA
(
PLayerid NUMBER(7),
firstname varchar2(255 char),
lastname varchar2(255 char),
Teamid NUMBER(7),
dateofbirth DATE,
social varchar2(255 char),
CONSTRAINT player_data_dept_fk FOREIGN KEY (teamid) REFERENCES SPORTS_TEAM(teamid));
