/*UPDATING SPORTS_TYPE FOR EACH TEAM*/
UPDATE SPORTS_TEAM
SET SPORTS_TYPE = 'NHL'
WHERE TEAMID = 1;

UPDATE SPORTS_TEAM
SET SPORTS_TYPE = 'NFL'
WHERE TEAMID = 2;

UPDATE SPORTS_TEAM
SET SPORTS_TYPE = 'NHL'
WHERE TEAMID = 3;

UPDATE SPORTS_TEAM
SET SPORTS_TYPE = 'NFL'
WHERE TEAMID = 4;

UPDATE SPORTS_TEAM
SET SPORTS_TYPE= 'NHL'
WHERE TEAMID = 5;

UPDATE SPORTS_TEAM
SET SPORTS_TYPE = 'NBA'
WHERE TEAMID = 6;

